### ISSUE TITLE
Prepopulate concept metadata by reading the file

### ISSUE THREAD

**Issue by dipasqualew** [photion/web-admin#22]
Files contain useful data that we can use to prepopulate the concept.

- [ ] File name can be used to name the Concept
- [ ] Read image metadata (tracked by #34) 
- [ ] Read video metadata (tracked by #35)
- [ ] Read sound metadata (tracked by #36)
