### ISSUE TITLE
TailwindCSS Migration: Replace Vuetify with Tailwind CSS

### ISSUE THREAD

**Issue by dipasqualew** [photion/web-admin#78]
Vuetify is heavy (consists of about 30% of our current bundle size) and outdated.

It is also the blocker for us to move to Vue 3.0 and possibly Vite (for faster builds).

It should be replaced with Tailwind CSS.

- [x] TailwindCSS Migration: Setup repo to use Tailwind CSS (tracked by #82)
- [x] TailwindCSS Migration: Layout and Landing page (tracked by #79)
- [x] TailwindCSS Migration: Services workflow (tracked by #80)
- [x] TailwindCSS Migration: Concepts workflow (tracked by #81)
- [ ] TailwindCSS Migration: TailwindCSS Migration: Calendar widget (tracked by #83)
- [ ] TailwindCSS Migration: Chips/Tags replacement (tracked by #84)
- [ ] TailwindCSS Migration: Chips/Tags replacement (requires all of the above)

**Comment by yurianxdev** [comment]
I'll pull-request removing Vuetify and the pages that depend on it. Then the Tailwind setup to start migrating pages to it.
